ALTER TABLE usuario ALTER dtype DEFAULT "Usuario";
ALTER TABLE usuario ALTER ativo DEFAULT true;


REPLACE INTO `role` VALUES (1,'ADMIN');
REPLACE INTO `role` VALUES (2,'AVALIADOR');
REPLACE INTO `role` VALUES (3,'ALUNO');

